### PR TITLE
Bit imports 6to5

### PR DESCRIPTION
**Pull request by MiguelCastillo**
@BrianGenisio Would you like to take a look?

### CODE REVIEW

**Comment by MiguelCastillo** [comment]
@BrianGenisio I have a little more work to do on this, but I wanted to at least get you to try it out.

* [ ] Make 6to5 browserified file a project that can be npm installed.

**Comment by BrianGenisio** [comment]
Cool.  Now that I'm back from vacation, I'll look at this for real.  Can you make sure that everything is working with the 6to5 3.0 release? It has changed it's name from 6to5 to babel so I am expecting that this PR needs a few names changed.

**Comment by MiguelCastillo** [comment]
Cool!  I am working through API documentation/publishing for bit imports maybe until tomorrow, but next on my list is figure out is how to best handle the rename to babel, which I am thinking will be really painless...  I need to see how babel is going to handle enabling specific version of ES.  Meaning, if I want ES6 only support - do I set a flag in babel or is there a babel ES6 specific build I need to use.  Hoping is build specific so that we don't cause bloat for features we are not yet interested in.

**Comment by BrianGenisio** [comment]
As far as I can tell, there is a `whitelist` and `blacklist` option which
lets you specify the features you want.  At a minimum, you can just list
the ES6 features.  I'm guessing there is a pre-defined list?

**Comment by MiguelCastillo** [comment]
Closed in favor of https://github.com/BrianGenisio/learnharmony/pull/10

**Pull request closed without merging**
